### ISSUE TITLE
Package signing fails when expect timeout is met

### ISSUE THREAD

**Issue by gpaiu** [jenkinsci/rpmsign-plugin#15]
On large packages, the plugin will silently fail as the expect timeout of 10 seconds is met:

```
[RpmSignPlugin] - Running rpm --define "_gpg_name *****************" --verbose --addsign /home/jenkinsbuild/workspace/*********/***.rpm
[****] $ expect -
spawn rpm --define _gpg_name ********* --verbose --addsign /home/jenkinsbuild/workspace/*********/***.rpm
Enter pass phrase: 
Pass phrase is good.
/home/jenkinsbuild/workspace/*********/***.rpm:
[RpmSignPlugin] - Finished signing RPMs ...
[RhnPush] - Starting publishing RPMs ...
[****] $ rhnpush --server=*** -u *** -p *** -c *** /home/jenkinsbuild/workspace/*********/***.rpm
ERROR: /home/jenkinsbuild/workspace/*********/***.rpm: unsigned rpm (use --nosig to force)
[RhnPush] - Failed publishing RPMs ...
Build step '[RhnPush] - Pushes RPMs to Spacewalk or RHN server' marked build as failure
```

Testing outside the Jenkins environment using a similar expect approach yields the same result. Only after adding a 'set timeout N' with any suitable value before the spawn would fix this. In my case the signing process took around 18 seconds. It would worth adding an option for this in the plugin configuration :). Thank you

**Comment by philfry** [comment]
Hi,
I've had the same problem, so as a workaround, I created a `.expect.rc` in jenkins' `$HOME`:
```
set timeout 600
```
Kind regards
Philippe

**Comment by gpaiu** [comment]
Thanks for the info Philippe 👍 , not sure if this is worth implementing in the plugin then since it's more of an environment configuration, so I'll close this down!
