### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by abohne** [jenkinsci/rpmsign-plugin#16]
Is this project still being maintained at all?  We have been using it, but are reconsidering since there hasn't been any activity in nearly 3 years.

**Comment by elibus** [comment]
Well, it works, no major issues found and the rpm interface did not change. Any specific improvements in mind?

**Comment by abohne** [comment]
@elibus sorry I missed your notification somehow.  Pipeline support would be a great addition.  @mbidewell anything else we're missing?

**Comment by mbidewell** [comment]
The default expect script timeout can be exceeded by a large RPM.  maybe make it configurable?

**Comment by abohne** [comment]
@elibus Sounds good.  We will test out the new version during our next jenkins upgrade and report back.
